version: '3'
services:
  zenfighter:
    build: .
    ports:
    - 8000:8000
    volumes:
    - .:/app
    links:
    - mysqldb
    environment:
      dbHost: "mysqldb"
      dbPort: "3306"
      dbName: "zenfighter"
      dbUser: "newguy"
      dbPass: "password123"
  mysqldb:
    image: mysql:5.7
    # volumes:
    # - /sql:/sql
    ports:
      - 3306:3306
    # command: --init-file /sql/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: zenfighter
      MYSQL_USER: newguy
      MYSQL_PASSWORD: password123
